import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import worker, { __test } from "../web/strategy-switch-console/worker.js";
import { DEFAULT_ACCOUNT_OPTIONS } from "../web/strategy-switch-console/config.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const indexHtml = [
  readFileSync(resolve(root, "web/strategy-switch-console/index.html"), "utf8"),
  readFileSync(resolve(root, "web/strategy-switch-console/app.css"), "utf8"),
  readFileSync(resolve(root, "web/strategy-switch-console/app.js"), "utf8"),
].join("\n");
const bundledStrategyProfiles = JSON.parse(
  readFileSync(resolve(root, "web/strategy-switch-console/strategy-profiles.example.json"), "utf8"),
);
assert.ok(__test.currentStrategiesTimeoutMs >= 8000);
const renderPlatformsBody = indexHtml.match(/function renderPlatforms\(\) \{([\s\S]*?)\n    \}/)?.[1] || "";
assert.ok(!renderPlatformsBody.includes("syncStrategyForAccount("));
assert.equal(indexHtml.includes(".innerHTML"), false);
assert.ok(indexHtml.includes('<body class="app-loading">'));
assert.ok(indexHtml.includes('id="boot-screen"'));
assert.ok(indexHtml.includes('id="app-shell"'));
assert.ok(indexHtml.includes(".switch-surface.summary-hidden"));
assert.ok(indexHtml.includes('summaryPanel.hidden = !showSummary'));
assert.ok(indexHtml.includes('switchSurface.classList.toggle("summary-hidden", !showSummary)'));
assert.equal(indexHtml.match(/Generated by inject_platform_config\.py/g)?.length, 1);
assert.equal(indexHtml.includes("publicSummary"), false);
assert.ok(indexHtml.includes("function hasPrivateConfig()"));
assert.ok(indexHtml.includes('el("quick-form").hidden = !showPrivateControls'));
assert.ok(indexHtml.includes("loginLink.hidden = signedIn"));
assert.equal(indexHtml.includes("loginLink.hidden = !state.auth.available || signedIn"), false);
assert.ok(indexHtml.includes('id="min-reserved-cash-input"'));
assert.ok(indexHtml.includes('id="reserved-cash-ratio-input"'));
assert.ok(indexHtml.includes('id="reserve-policy-mode-select"'));
assert.ok(indexHtml.includes('id="runtime-target-enabled-select"'));
assert.ok(indexHtml.includes('id="plugin-mode-select"'));
assert.equal(indexHtml.includes('id="ibit-zscore-exit-mode-select"'), false);
assert.ok(indexHtml.includes('id="income-layer-start-usd-input"'));
assert.ok(indexHtml.includes('incomeLayerStartUsd: "收入层起始金额"'));
assert.ok(indexHtml.includes('incomeLayerStartUsd: "Income layer start amount"'));
assert.ok(indexHtml.includes('incomeLayerStartUsdVariable = "INCOME_LAYER_START_USD"'));
assert.ok(indexHtml.includes("fallbackIncomeLayerDefaults"));
assert.ok(indexHtml.includes("incomeLayerDefaultsFromProfileItem"));
assert.ok(indexHtml.includes('id="option-overlay-mode-select"'));
assert.ok(indexHtml.includes('optionOverlayMode: "期权层状态"'));
assert.ok(indexHtml.includes('optionOverlayMode: "Option layer"'));
assert.ok(indexHtml.includes("optionOverlayDefaultsFromProfileItem"));
assert.ok(indexHtml.includes('id="cash-only-execution-mode-select"'));
assert.ok(indexHtml.includes('class="form-section execution-cash-policy-section"'));
assert.ok(indexHtml.includes('function reconcileExecutionCashPolicy('));
assert.ok(indexHtml.includes('qmt: { label: "QMT"'));
assert.ok(indexHtml.includes('cn_industry_etf_rotation'));
assert.ok(indexHtml.includes('id="income-layer-section"'));
assert.ok(indexHtml.includes('id="option-overlay-section"'));
assert.equal(indexHtml.includes('id="margin-policy-stack"'), false);
assert.equal(indexHtml.includes('id="reserve-policy-stack"'), false);
assert.equal(indexHtml.includes('id="reserve-amounts-row"'), false);
assert.ok(indexHtml.includes('id="min-reserve-block"'));
assert.ok(indexHtml.includes('id="reserve-ratio-block"'));
assert.ok(indexHtml.includes("cash_only_execution_mode: item.cash_only_execution_mode"));
assert.ok(indexHtml.includes("function incomeLayerFieldsConfigured("));
assert.ok(indexHtml.includes("function effectiveIncomeLayerForAccount("));
assert.ok(indexHtml.includes('class="summary-list" id="summary-list" role="list"'));
assert.ok(indexHtml.includes('labelNode.className = "summary-label"'));
assert.equal(indexHtml.includes("noChangesNote"), false);
assert.equal(indexHtml.match(/class="form-section dca-section"/g)?.length, 1);
assert.ok(indexHtml.includes('qmtDryRunOnlyNote'));
assert.ok(indexHtml.includes('optionOverlayDefaultSimple: "开启"'));
assert.ok(indexHtml.includes('cashOnlyExecutionDefault: "仅用现金"'));
assert.match(indexHtml, /function platformCashOnlyExecutionDefault\(\) \{\s+return true;/);
assert.ok(indexHtml.includes("function effectiveOptionOverlayForAccount("));
assert.ok(indexHtml.includes("selectedAccount(platform)?.option_overlay_mode"));
assert.ok(indexHtml.includes("function effectiveCashOnlyExecutionForAccount("));
assert.ok(indexHtml.includes('cashOnlyExecutionValueYes: "是"'));
assert.ok(indexHtml.includes('cashOnlyExecutionMode: "Allow margin"'));
assert.ok(indexHtml.includes('el("cash-only-execution-mode-select").addEventListener("change"'));
assert.ok(indexHtml.includes("function pendingCashOnlyExecution("));
assert.ok(indexHtml.includes('!platformSupportsMarginPolicy(platform) || mode === "current"'));
assert.ok(indexHtml.includes("function syncCashOnlyExecutionForAccount("));
assert.equal(indexHtml.includes('id="option-growth-overlay'), false);
assert.equal(indexHtml.includes('id="option-income-overlay'), false);
assert.ok(indexHtml.includes('id="dca-mode-select"'));
assert.ok(indexHtml.includes('id="dca-base-investment-usd-input"'));
assert.ok(indexHtml.includes('dcaMode: "定投模式"'));
assert.ok(indexHtml.includes('dcaModeFixed: "定额定投"'));
assert.ok(indexHtml.includes('dcaModeSmart: "智能定投"'));
assert.ok(indexHtml.includes('dcaMode: "DCA mode"'));
assert.ok(indexHtml.includes('dcaProfileDefaults'));
assert.ok(indexHtml.includes('el("income-layer-mode-select").addEventListener("change"'));
assert.ok(indexHtml.includes('el("income-layer-start-usd-input").addEventListener("input"'));
assert.ok(indexHtml.includes('el("income-layer-max-ratio-input").addEventListener("input"'));
assert.ok(indexHtml.includes('el("dca-mode-select").addEventListener("change"'));
assert.ok(indexHtml.includes('el("dca-base-investment-usd-input").addEventListener("input"'));
assert.ok(
	  indexHtml.includes('"label_zh": "纳指100 / 标普500 定投"') ||
	  indexHtml.includes('"label_zh": "纳指标普定投"'),
	);
assert.ok(indexHtml.includes('class="form-section income-layer-section"'));
assert.ok(indexHtml.includes('class="form-section dca-section"'));
assert.ok(indexHtml.includes('class="control-block reserve-policy-block policy-block"'));
assert.ok(indexHtml.includes('"profile": "ibit_smart_dca"'));
for (const profile of bundledStrategyProfiles) {
  assert.ok(indexHtml.includes(`"profile": ${JSON.stringify(profile.profile)}`), `fallback missing ${profile.profile}`);
  assert.ok(indexHtml.includes(`"label_en": ${JSON.stringify(profile.label_en)}`), `fallback English label mismatch for ${profile.profile}`);
  assert.ok(indexHtml.includes(`"label_zh": ${JSON.stringify(profile.label_zh)}`), `fallback Chinese label mismatch for ${profile.profile}`);
}
assert.ok(indexHtml.includes('localStrategyLabels'));
assert.ok(indexHtml.includes('function strategyLabelSet('));
assert.ok(indexHtml.includes('function strategyDisplayMetaText('));
assert.ok(indexHtml.includes('function strategyChoiceLabel('));
assert.ok(indexHtml.includes('function strategyCanSwitchLive('));
assert.ok(indexHtml.includes("account-block"));
assert.ok(indexHtml.includes("strategy-block"));
assert.ok(indexHtml.includes("white-space: pre-line"));
assert.ok(indexHtml.includes(".form-section {"));
assert.ok(indexHtml.includes(".form-section + .form-section"));
assert.ok(indexHtml.includes("grid-template-columns: repeat(2, minmax(0, 1fr));"));
assert.ok(indexHtml.includes("grid-column: 1 / -1;"));
assert.ok(indexHtml.includes('reservePolicyNone'));
assert.ok(indexHtml.includes('reservePolicyRatio'));
assert.ok(indexHtml.includes('reservePolicyFloor'));
assert.ok(indexHtml.includes('reservePolicyMax'));
assert.ok(indexHtml.includes('pluginModeAuto'));
assert.ok(indexHtml.includes('pluginModeNone'));
assert.ok(indexHtml.includes('runtimeTargetMode: "账号运行状态"'));
assert.ok(indexHtml.includes('runtimeTargetEnabled: "启用"'));
assert.ok(indexHtml.includes('runtimeTargetDisabled: "禁用"'));
assert.ok(indexHtml.includes('runtimeTargetMode: "Account status"'));
assert.ok(indexHtml.includes('runtimeTargetEnabled: "Enabled"'));
assert.ok(indexHtml.includes('runtimeTargetDisabled: "Disabled"'));
assert.ok(indexHtml.includes("function runtimeTargetStateForAccount("));
assert.ok(indexHtml.includes(".summary-status.disabled"));
assert.ok(indexHtml.includes('pluginMode: "插件启用范围"'));
assert.ok(indexHtml.includes('pluginModeAuto: "启用插件"'));
assert.ok(indexHtml.includes('pluginModeNone: "禁用插件"'));
assert.ok(indexHtml.includes('pluginModeAuto: "Enabled"'));
assert.ok(indexHtml.includes('pluginMode: "Plugin scope"'));
assert.equal(indexHtml.includes('id="ibit-zscore-exit-mode-select"'), false);
assert.equal(indexHtml.includes("ibitZscoreExit"), false);
assert.equal(indexHtml.includes("ibit_zscore_exit_mode"), false);
assert.ok(indexHtml.includes('reservedCashDefault'));
assert.ok(indexHtml.includes('paper: "模拟"'));
assert.ok(indexHtml.includes('paper: "Dry run"'));
assert.ok(indexHtml.includes('平台默认：0 {currency} / 0%'));
assert.equal(indexHtml.includes('比例沿用策略默认，通常 3%'), false);
assert.equal(indexHtml.includes('平台默认：max(0 {currency}, 3%)'), false);
assert.ok(indexHtml.includes('function platformReservedCashDefaultText('));
assert.ok(indexHtml.includes('platformMinReservedCashVariables'));
assert.ok(indexHtml.includes('platformReservedCashRatioVariables'));
assert.ok(indexHtml.includes('extra_variables_json'));
assert.ok(indexHtml.includes('function selectedCashCurrency('));
assert.ok(indexHtml.includes('function currentReservedCashPolicyText('));
assert.ok(indexHtml.includes('function hasPendingChanges('));
assert.ok(indexHtml.includes('function pendingChangeState('));
assert.ok(indexHtml.includes('reservedCashTouched: false'));
assert.ok(indexHtml.includes('reserve-ratio-block'));
assert.ok(indexHtml.includes('.summary-row.pending'));
assert.ok(indexHtml.includes('function currentEntryHasState('));
assert.ok(indexHtml.includes('changes.reserveCashChanged'));
assert.ok(indexHtml.includes('changes.pluginModeChanged'));
assert.ok(indexHtml.includes('changes.runtimeTargetChanged'));
assert.ok(indexHtml.includes('!hasPendingChange'));
assert.ok(indexHtml.includes('hasPendingChange ? t("readyNote") : ""'));
assert.equal(indexHtml.includes('hasPendingChange ? t("readyNote") : t("noChangesNote")'), false);
assert.equal(
  indexHtml.includes('state.auth.allowed && !loadingConfig && (!hasPrivateAccounts || !hasValidStrategy || !hasPendingChange)'),
  false,
);
assert.equal(indexHtml.includes('placeholder="150"'), false);
assert.equal(indexHtml.includes('placeholder="0.03"'), false);
assert.equal(indexHtml.includes("ibkr-primary"), false);
assert.equal(indexHtml.includes("longbridge-quant-sg-service"), false);
assert.equal(indexHtml.includes('account_selector: "SG"'), false);
assert.match(indexHtml, /body\.app-loading \.shell\s*\{\s*display: none;/);

const servedPageResponse = await worker.fetch(new Request("https://switch.example/"), {});
const servedHtml = await servedPageResponse.text();
assert.equal(servedPageResponse.status, 200);
assert.equal(servedHtml.includes("ibkr-primary"), false);
assert.equal(servedHtml.includes("longbridge-quant-sg-service"), false);
assert.equal(servedHtml.includes('account_selector: "SG"'), false);

const servedAppResponse = await worker.fetch(new Request("https://switch.example/app.js"), {});
const servedAppJs = await servedAppResponse.text();
assert.equal(servedAppResponse.status, 200);
assert.ok(servedAppJs.includes("function hasPrivateConfig()"));
assert.equal(servedAppJs.includes("ibitZscoreExit"), false);
assert.equal(servedAppJs.includes("ibit_zscore_exit_mode"), false);
assert.equal(servedAppJs.includes("ibkr-primary"), false);
assert.equal(servedAppJs.includes("longbridge-quant-sg-service"), false);
assert.equal(servedAppJs.includes('account_selector: "SG"'), false);

const publicConfigResponse = await worker.fetch(new Request("https://switch.example/api/config"), {});
assert.equal(publicConfigResponse.status, 200);
const publicConfig = await publicConfigResponse.json();
assert.equal(publicConfig.accountOptions, null);
assert.ok(publicConfig.platformMeta?.longbridge?.label === "LongBridge");

assert.equal(
  __test.platformRepositories({ STRATEGY_SWITCH_LONGBRIDGE_REPO: "ForkOrg/LongBridgePlatform" }).longbridge,
  "ForkOrg/LongBridgePlatform",
);
assert.equal(
  __test.platformRepositories({
    RUNTIME_SETTINGS_PLATFORM_REPOSITORIES_JSON: JSON.stringify({
      ibkr: "ForkOrg/InteractiveBrokersPlatform",
    }),
  }).ibkr,
  "ForkOrg/InteractiveBrokersPlatform",
);

const headers = __test.responseHeaders({ "Content-Type": "text/html; charset=utf-8" });
assert.equal(headers.get("X-Frame-Options"), "DENY");
assert.equal(headers.get("X-Content-Type-Options"), "nosniff");
assert.equal(headers.get("Referrer-Policy"), "no-referrer");
assert.match(headers.get("Content-Security-Policy") || "", /frame-ancestors 'none'/);

assert.doesNotThrow(() => __test.requireSameOrigin(
  new Request("https://switch.example/api/switch", {
    method: "POST",
    headers: { Origin: "https://switch.example" },
  }),
  { requireOrigin: true },
));
const missingOriginError = captureError(
  () => __test.requireSameOrigin(new Request("https://switch.example/api/switch", { method: "POST" }), {
    requireOrigin: true,
  }),
);
assert.match(missingOriginError.message, /Origin header is required/);
assert.equal(missingOriginError.status, 403);
const crossOriginError = captureError(
  () => __test.requireSameOrigin(
    new Request("https://switch.example/api/switch", {
      method: "POST",
      headers: { Origin: "https://evil.example" },
    }),
    { requireOrigin: true },
  ),
);
assert.match(crossOriginError.message, /cross-origin request rejected/);
assert.equal(crossOriginError.status, 403);

const unauthorizedSyncResponse = await worker.fetch(
  new Request("https://switch.example/api/internal/sync-account-default", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: "{}",
  }),
  { STRATEGY_SWITCH_SYNC_TOKEN: "test-sync-token" },
);
assert.equal(unauthorizedSyncResponse.status, 401);
assert.match((await unauthorizedSyncResponse.json()).error, /internal sync token is invalid/);

const unauthorizedProfileSyncResponse = await worker.fetch(
  new Request("https://switch.example/api/internal/sync-strategy-profiles", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: "{}",
  }),
  { STRATEGY_SWITCH_SYNC_TOKEN: "test-sync-token" },
);
assert.equal(unauthorizedProfileSyncResponse.status, 401);
assert.match((await unauthorizedProfileSyncResponse.json()).error, /internal sync token is invalid/);

assert.equal(
  await __test.withTimeout(new Promise(() => {}), 1, "fallback"),
  "fallback",
);
const timeoutFetchResponse = await __test.fetchWithTimeout(
  "https://api.github.test/user",
  { headers: { Accept: "application/json" } },
  100,
  async (_resource, init) => {
    assert.ok(init.signal instanceof AbortSignal);
    assert.equal(init.headers.Accept, "application/json");
    return new Response('{"ok":true}', { status: 200 });
  },
);
assert.equal(timeoutFetchResponse.status, 200);
await assert.rejects(
  () => __test.fetchWithTimeout(
    "https://api.github.test/slow",
    {},
    1,
    (_resource, init) => new Promise((_resolve, reject) => {
      init.signal.addEventListener("abort", () => {
        const error = new Error("aborted");
        error.name = "AbortError";
        reject(error);
      });
    }),
  ),
  /GitHub request timed out/,
);

function captureError(fn) {
  try {
    fn();
  } catch (error) {
    return error;
  }
  assert.fail("Expected function to throw");
}

const strategyProfiles = __test.normalizeStrategyProfilesPayload(
  [
    {
      profile: "tqqq_growth_income",
      label: "TQQQ Growth Income",
      label_zh: "TQQQ 增长收益",
      domain: "us_equity",
      runtime_enabled: true,
      lifecycle_stage: "live",
      can_switch_live: true,
      allowed_execution_modes: ["live", "paper"],
      income_layer_enabled: true,
      income_layer_start_usd: "250000",
      income_layer_max_ratio: "0.55",
      income_layer_allocations: { SCHD: 0.3, DGRO: 0.2, SGOV: 0.4, SPYI: 0.08, QQQI: 0.02 },
      option_overlay_enabled: true,
      option_overlay_live_gate: "promotion_required",
      option_overlay_live_status: "research_only",
      latest_evidence_status: "live_allowed",
      plugin_gate_status: "live_allowed",
      option_growth_overlay_enabled: true,
      option_growth_overlay_recipe: "tqqq_leaps_growth_v1",
      option_growth_overlay_start_usd: "250000",
      option_growth_overlay_nav_budget_ratio: "0.03",
      option_income_overlay_enabled: false,
    },
    {
      profile: "hk_low_vol_dividend_quality_snapshot",
      label: "HK Low-Vol Dividend Quality Snapshot",
      domain: "hk_equity",
      runtime_enabled: true,
    },
    {
      profile: "us_equity_combo_leveraged",
      label: "US Alpha Combo",
      domain: "us_equity",
      runtime_enabled: true,
      lifecycle_stage: "research",
      can_switch_live: false,
      allowed_execution_modes: ["paper"],
      blocked_live_reason: "promotion_required",
      latest_evidence_status: "research_only",
      plugin_gate_status: "blocked",
    },
    {
      profile: "nasdaq_sp500_smart_dca",
      label: "Nasdaq 100 / S&P 500 DCA",
      label_zh: "纳指100 / 标普500 定投",
      domain: "us_equity",
      runtime_enabled: true,
    },
  ],
  "test_strategy_profiles",
);
assert.equal(strategyProfiles[0].label_en, "TQQQ Growth Income");
assert.equal(strategyProfiles[0].label_zh, "TQQQ 增长收益");
assert.equal(strategyProfiles[0].lifecycle_stage, "live");
assert.equal(strategyProfiles[0].can_switch_live, true);
assert.deepEqual(strategyProfiles[0].allowed_execution_modes, ["live", "paper"]);
assert.equal(strategyProfiles[0].income_layer_enabled, true);
assert.equal(strategyProfiles[0].income_layer_start_usd, "250000");
assert.equal(strategyProfiles[0].income_layer_max_ratio, "0.55");
assert.deepEqual(strategyProfiles[0].income_layer_allocations, {
  SCHD: 0.3,
  DGRO: 0.2,
  SGOV: 0.4,
  SPYI: 0.08,
  QQQI: 0.02,
});
assert.equal(strategyProfiles[0].option_overlay_enabled, true);
assert.equal(strategyProfiles[0].option_overlay_live_gate, "promotion_required");
assert.equal(strategyProfiles[0].option_overlay_live_status, "research_only");
assert.equal(strategyProfiles[0].option_growth_overlay_enabled, true);
assert.equal(strategyProfiles[0].option_growth_overlay_recipe, "tqqq_leaps_growth_v1");
assert.equal(strategyProfiles[0].option_growth_overlay_start_usd, "250000");
assert.equal(strategyProfiles[0].option_growth_overlay_nav_budget_ratio, "0.03");
assert.equal(strategyProfiles[0].option_income_overlay_enabled, false);
assert.equal(strategyProfiles[0].latest_evidence_status, "live_allowed");
assert.equal(strategyProfiles[0].plugin_gate_status, "live_allowed");
assert.equal(strategyProfiles[2].lifecycle_stage, "research");
assert.equal(strategyProfiles[2].can_switch_live, false);
assert.deepEqual(strategyProfiles[2].allowed_execution_modes, ["paper"]);
assert.equal(strategyProfiles[2].blocked_live_reason, "promotion_required");
assert.equal(strategyProfiles[2].latest_evidence_status, "research_only");
assert.equal(strategyProfiles[2].plugin_gate_status, "blocked");
assert.equal(strategyProfiles[3].dca_enabled, true);
assert.equal(strategyProfiles[3].dca_default_mode, "fixed");
assert.equal(strategyProfiles[3].dca_default_base_investment_usd, "1000");

assert.doesNotThrow(() =>
  __test.assertStrategyAllowedForAccount(
    { platform: "longbridge", strategy_profile: "tqqq_growth_income", execution_mode: "live" },
    DEFAULT_ACCOUNT_OPTIONS.longbridge[0],
    strategyProfiles,
  ),
);
assert.throws(
  () =>
    __test.assertStrategyAllowedForAccount(
      { platform: "longbridge", strategy_profile: "us_equity_combo_leveraged", execution_mode: "live" },
      DEFAULT_ACCOUNT_OPTIONS.longbridge[0],
      strategyProfiles,
    ),
  /not live-enabled/,
);
assert.doesNotThrow(() =>
  __test.assertStrategyAllowedForAccount(
    { platform: "longbridge", strategy_profile: "us_equity_combo_leveraged", execution_mode: "paper" },
    DEFAULT_ACCOUNT_OPTIONS.longbridge[0],
    strategyProfiles,
  ),
);

const accountOptions = __test.normalizeAccountOptionsPayload(
  {
    longbridge: [
      {
        key: "hk",
        label: "hk",
        target_name: "hk",
        account_selector: "HK",
        cash_currency: "HKD",
      },
      {
        key: "sg",
        label: "sg",
        target_name: "sg",
        account_selector: "SG",
      },
    ],
    ibkr: [
      {
        key: "ibkr-primary",
        label: "ibkr-primary",
        target_name: "ibkr-primary",
        account_selector: "DEMO_IBKR_PRIMARY",
        deployment_selector: "demo-ibkr-tqqq",
        account_scope: "demo-ibkr-tqqq",
        service_name: "interactive-brokers-demo-ibkr-tqqq-service",
      },
    ],
    schwab: [
      {
        key: "default",
        label: "default",
        target_name: "default",
        supported_domains: ["us_equity"],
      },
    ],
    firstrade: [
      {
        key: "default",
        label: "default",
        target_name: "default",
        supported_domains: ["us_equity"],
      },
    ],
  },
  "test_account_options",
);

assert.deepEqual(accountOptions.longbridge[0].supported_domains, ["us_equity", "hk_equity"]);
assert.deepEqual(accountOptions.longbridge[1].supported_domains, ["us_equity", "hk_equity"]);
assert.deepEqual(accountOptions.ibkr[0].supported_domains, ["us_equity", "hk_equity"]);
assert.equal(accountOptions.longbridge[0].cash_currency, "HKD");
const defaultAccountOptions = __test.normalizeAccountOptionsPayload(DEFAULT_ACCOUNT_OPTIONS, "default_account_options");
assert.equal(defaultAccountOptions.qmt[0].cash_currency, "CNY");
for (const platformOptions of Object.values(DEFAULT_ACCOUNT_OPTIONS)) {
  for (const option of platformOptions) {
    assert.equal("reserved_cash_ratio" in option, false);
    assert.equal("min_reserved_cash_usd" in option, false);
  }
}

const accountOptionsWithCashOnlyMode = __test.normalizeAccountOptionsPayload(
  {
    longbridge: [
      {
        key: "sg",
        label: "sg",
        target_name: "sg",
        cash_only_execution_mode: "enabled",
      },
    ],
  },
  "test_account_options",
);
assert.equal(accountOptionsWithCashOnlyMode.longbridge[0].cash_only_execution_mode, "enabled");

const accountOptionsWithOptionOverlayMode = __test.normalizeAccountOptionsPayload(
  {
    ibkr: [
      {
        key: "ibkr-primary",
        label: "ibkr-primary",
        target_name: "ibkr-primary",
        option_overlay_mode: "disabled",
      },
    ],
  },
  "test_account_options",
);
assert.equal(accountOptionsWithOptionOverlayMode.ibkr[0].option_overlay_mode, "disabled");

const kvUnboundSyncResponse = await worker.fetch(
  new Request("https://switch.example/api/internal/sync-account-default", {
    method: "POST",
    headers: {
      Authorization: "Bearer test-sync-token",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      platform: "ibkr",
      target_name: "ibkr-primary",
      account_selector: "DEMO_IBKR_PRIMARY",
      deployment_selector: "demo-ibkr-tqqq",
      account_scope: "demo-ibkr-tqqq",
      service_name: "interactive-brokers-demo-ibkr-tqqq-service",
      strategy_profile: "tqqq_growth_income",
      execution_mode: "live",
      variable_scope: "default",
      plugin_mode: "auto",
      option_overlay_mode: "current",
      cash_only_execution_mode: "current",
    }),
  }),
  {
    STRATEGY_SWITCH_SYNC_TOKEN: "test-sync-token",
    STRATEGY_SWITCH_ACCOUNT_OPTIONS_JSON: JSON.stringify(accountOptions),
    STRATEGY_SWITCH_STRATEGY_PROFILES_JSON: JSON.stringify(strategyProfiles),
  },
);
assert.equal(kvUnboundSyncResponse.status, 200);
const kvUnboundSyncBody = await kvUnboundSyncResponse.json();
assert.equal(kvUnboundSyncBody.ok, true);
assert.deepEqual(kvUnboundSyncBody.account_options_sync, {
  synced: false,
  reason: "kv_not_bound",
  skipped: true,
});

const kvUnboundProfileSyncResponse = await worker.fetch(
  new Request("https://switch.example/api/internal/sync-strategy-profiles", {
    method: "POST",
    headers: {
      Authorization: "Bearer test-sync-token",
      "Content-Type": "application/json",
    },
    body: "{}",
  }),
  { STRATEGY_SWITCH_SYNC_TOKEN: "test-sync-token" },
);
assert.equal(kvUnboundProfileSyncResponse.status, 200);
const kvUnboundProfileSyncBody = await kvUnboundProfileSyncResponse.json();
assert.equal(kvUnboundProfileSyncBody.ok, true);
assert.equal(kvUnboundProfileSyncBody.strategy_profiles_sync.reason, "kv_not_bound");
assert.equal(kvUnboundProfileSyncBody.strategy_profiles_sync.skipped, true);

const profileKvWrites = new Map();
const profileSyncResponse = await worker.fetch(
  new Request("https://switch.example/api/internal/sync-strategy-profiles", {
    method: "POST",
    headers: {
      Authorization: "Bearer test-sync-token",
      "Content-Type": "application/json",
    },
    body: "{}",
  }),
  {
    STRATEGY_SWITCH_SYNC_TOKEN: "test-sync-token",
    STRATEGY_SWITCH_CONFIG: {
      get: async (key) => (key === "strategy_profiles" ? JSON.stringify([{ profile: "stale" }]) : null),
      put: async (key, value) => profileKvWrites.set(key, value),
    },
  },
);
assert.equal(profileSyncResponse.status, 200);
const profileSyncBody = await profileSyncResponse.json();
assert.equal(profileSyncBody.ok, true);
assert.equal(profileSyncBody.strategy_profiles_sync.synced, true);
assert.equal(profileSyncBody.strategy_profiles_sync.changed, true);
assert.ok(JSON.parse(profileKvWrites.get("strategy_profiles")).some((item) => item.profile === "ibit_smart_dca"));

const normalizedReservedCashInputs = __test.normalizeSwitchInputs({
  platform: "ibkr",
  target_name: "ibkr-primary",
  strategy_profile: "tqqq_growth_income",
  execution_mode: "live",
  account_selector: "DEMO_IBKR_PRIMARY",
  deployment_selector: "demo-ibkr-tqqq",
  account_scope: "demo-ibkr-tqqq",
  service_name: "interactive-brokers-demo-ibkr-tqqq-service",
  apply: "true",
  trigger_platform_sync: "true",
  reserved_cash_ratio: "0.03",
  min_reserved_cash_usd: "150",
  income_layer_start_usd: "250000",
  income_layer_max_ratio: "0.55",
  option_overlay_mode: "enabled",
});
assert.equal(normalizedReservedCashInputs.reserved_cash_ratio, "0.03");
assert.equal(normalizedReservedCashInputs.min_reserved_cash_usd, "150");
assert.equal(normalizedReservedCashInputs.income_layer_start_usd, "250000");
assert.equal(normalizedReservedCashInputs.income_layer_max_ratio, "0.55");
assert.equal(normalizedReservedCashInputs.option_overlay_mode, "enabled");
const normalizedCashOnlyInputs = __test.normalizeSwitchInputs({
  platform: "ibkr",
  target_name: "ibkr-primary",
  strategy_profile: "tqqq_growth_income",
  execution_mode: "live",
  cash_only_execution_mode: "disabled",
});
assert.equal(normalizedCashOnlyInputs.cash_only_execution_mode, undefined);
assert.deepEqual(JSON.parse(normalizedCashOnlyInputs.extra_variables_json), {
  cash_only_execution_mode: "disabled",
});
assert.equal("cash_only_execution_mode" in normalizedCashOnlyInputs, false);

const workflowYaml = readFileSync(resolve(root, ".github/workflows/manual-strategy-switch.yml"), "utf8");
const workflowInputs = [...workflowYaml.matchAll(/^      ([A-Za-z0-9_]+):\n        description:/gm)].map((match) => match[1]);
const dispatchInputs = __test.normalizeSwitchInputs({
  platform: "ibkr",
  target_name: "ibkr-primary",
  strategy_profile: "tqqq_growth_income",
  execution_mode: "live",
  cash_only_execution_mode: "enabled",
  apply: "true",
  trigger_platform_sync: "true",
  confirm_apply: "APPLY_AND_SYNC",
});
for (const key of Object.keys(dispatchInputs)) {
  assert.ok(workflowInputs.includes(key), `workflow input missing for dispatch field: ${key}`);
}
const normalizedPluginInputs = __test.normalizeSwitchInputs({
  platform: "ibkr",
  target_name: "ibkr-primary",
  strategy_profile: "tqqq_growth_income",
  execution_mode: "live",
  plugin_mode: "none",
});
assert.equal(normalizedPluginInputs.plugin_mode, "none");
const normalizedDcaInputs = __test.normalizeSwitchInputs({
  platform: "firstrade",
  target_name: "default",
  strategy_profile: "nasdaq_sp500_smart_dca",
  execution_mode: "live",
  plugin_mode: "auto",
  dca_mode: "smart",
  dca_base_investment_usd: "500",
});
assert.equal(normalizedDcaInputs.dca_mode, undefined);
assert.equal(normalizedDcaInputs.dca_base_investment_usd, undefined);
assert.deepEqual(JSON.parse(normalizedDcaInputs.extra_variables_json), {
  dca_mode: "smart",
  dca_base_investment_usd: "500",
  cash_only_execution_mode: "enabled",
});
const normalizedIbkrDcaInputs = __test.normalizeSwitchInputs({
  platform: "ibkr",
  target_name: "ibkr-primary",
  strategy_profile: "nasdaq_sp500_smart_dca",
  execution_mode: "live",
  plugin_mode: "auto",
  dca_mode: "smart",
  dca_base_investment_usd: "500",
});
assert.deepEqual(JSON.parse(normalizedIbkrDcaInputs.extra_variables_json), {
  dca_mode: "smart",
  dca_base_investment_usd: "500",
  cash_only_execution_mode: "enabled",
});
const normalizedDcaJsonInputs = __test.normalizeSwitchInputs({
  platform: "firstrade",
  target_name: "default",
  strategy_profile: "nasdaq_sp500_smart_dca",
  execution_mode: "live",
  plugin_mode: "auto",
  extra_variables_json: JSON.stringify({
    dca_mode: "smart",
    dca_base_investment_usd: "500",
  }),
});
assert.deepEqual(JSON.parse(normalizedDcaJsonInputs.extra_variables_json), {
  dca_mode: "smart",
  dca_base_investment_usd: "500",
  cash_only_execution_mode: "enabled",
});
const normalizedIbitSmartDcaInputs = __test.normalizeSwitchInputs({
  platform: "firstrade",
  target_name: "default",
  strategy_profile: "ibit_smart_dca",
  execution_mode: "live",
  plugin_mode: "auto",
  dca_mode: "smart",
  dca_base_investment_usd: "500",
  ibit_zscore_exit_mode: "live",
});
assert.deepEqual(JSON.parse(normalizedIbitSmartDcaInputs.extra_variables_json), {
  dca_mode: "smart",
  dca_base_investment_usd: "500",
  cash_only_execution_mode: "enabled",
});
const normalizedIbkrIbitSmartDcaInputs = __test.normalizeSwitchInputs({
  platform: "ibkr",
  target_name: "ibit-primary",
  strategy_profile: "ibit_smart_dca",
  execution_mode: "live",
  plugin_mode: "auto",
  extra_variables_json: JSON.stringify({
    dca_mode: "smart",
    dca_base_investment_usd: "500",
    ibit_zscore_exit_mode: "live",
  }),
});
assert.deepEqual(JSON.parse(normalizedIbkrIbitSmartDcaInputs.extra_variables_json), {
  dca_mode: "smart",
  dca_base_investment_usd: "500",
  cash_only_execution_mode: "enabled",
});
const normalizedNonIbitLegacyZscoreInputs = __test.normalizeSwitchInputs({
  platform: "ibkr",
  target_name: "ibkr-primary",
  strategy_profile: "tqqq_growth_income",
  execution_mode: "live",
  extra_variables_json: JSON.stringify({ ibit_zscore_exit_mode: "live" }),
});
assert.deepEqual(JSON.parse(normalizedNonIbitLegacyZscoreInputs.extra_variables_json), {
  cash_only_execution_mode: "enabled",
});
assert.throws(
  () => __test.normalizeSwitchInputs({
    platform: "qmt",
    target_name: "industry_etf_dry_run",
    strategy_profile: "cn_industry_etf_rotation",
    execution_mode: "live",
  }),
  /does not support live execution yet/,
);
const normalizedQmtDryRunInputs = __test.normalizeSwitchInputs({
  platform: "qmt",
  target_name: "industry_etf_dry_run",
  strategy_profile: "cn_industry_etf_rotation",
  execution_mode: "paper",
});
assert.equal(normalizedQmtDryRunInputs.execution_mode, "paper");
assert.throws(
  () => __test.normalizeSwitchInputs({
    platform: "ibkr",
    target_name: "ibkr-primary",
    strategy_profile: "tqqq_growth_income",
    dca_mode: "smart",
  }),
  /DCA settings are only supported/,
);
assert.throws(
  () => __test.normalizeSwitchInputs({
    platform: "firstrade",
    target_name: "default",
    strategy_profile: "nasdaq_sp500_smart_dca",
    dca_mode: "smart",
    dca_base_investment_usd: "0",
  }),
  /dca_base_investment_usd must be greater than 0/,
);
assert.throws(
  () => __test.normalizeSwitchInputs({
    platform: "ibkr",
    target_name: "ibkr-primary",
    strategy_profile: "tqqq_growth_income",
    extra_variables_json: JSON.stringify({ DCA_MODE: "smart" }),
  }),
  /control fields/,
);
assert.throws(
  () => __test.normalizeSwitchInputs({
    platform: "ibkr",
    target_name: "ibkr-primary",
    strategy_profile: "tqqq_growth_income",
    extra_variables_json: JSON.stringify({ option_growth_overlay_enabled: "true" }),
  }),
  /research-only/,
);
assert.throws(
  () => __test.normalizeSwitchInputs({
    platform: "ibkr",
    target_name: "ibkr-primary",
    strategy_profile: "tqqq_growth_income",
    extra_variables_json: JSON.stringify({ INCOME_THRESHOLD_USD: "250000" }),
  }),
  /research-only/,
);
const normalizedReserveClearInputs = __test.normalizeSwitchInputs({
  platform: "ibkr",
  target_name: "ibkr-primary",
  strategy_profile: "tqqq_growth_income",
  execution_mode: "live",
  extra_variables_json: JSON.stringify({
    IBKR_MIN_RESERVED_CASH_USD: "",
    IBKR_RESERVED_CASH_RATIO: "",
  }),
});
assert.deepEqual(JSON.parse(normalizedReserveClearInputs.extra_variables_json), {
  IBKR_MIN_RESERVED_CASH_USD: "",
  IBKR_RESERVED_CASH_RATIO: "",
  cash_only_execution_mode: "enabled",
});
assert.throws(
  () => __test.normalizeSwitchInputs({
    platform: "ibkr",
    target_name: "ibkr-primary",
    strategy_profile: "tqqq_growth_income",
    extra_variables_json: JSON.stringify({ IBKR_CASH_ONLY_EXECUTION: "true" }),
  }),
  /cash_only_execution_mode instead of CASH_ONLY_EXECUTION/,
);
assert.throws(
  () => __test.normalizeSwitchInputs({
    platform: "ibkr",
    target_name: "ibkr-primary",
    strategy_profile: "tqqq_growth_income",
    reserved_cash_ratio: "1.25",
  }),
  /reserved_cash_ratio must be between 0 and 1/,
);

const updatedAccountOptions = __test.updateAccountOptionsDefaultStrategy(
  accountOptions,
  {
    platform: "longbridge",
    target_name: "sg",
    account_selector: "SG",
    deployment_selector: "SG",
    account_scope: "SG",
    service_name: "longbridge-quant-sg-service",
    github_environment: "longbridge-sg",
    strategy_profile: "soxl_soxx_trend_income",
    execution_mode: "live",
    variable_scope: "environment",
    plugin_mode: "auto",
  },
);
// default_strategy_profile update removed — only other fields may change
assert.equal(
  __test.accountOptionMatchesInputs(
    { target_name: "sg", variable_scope: "default" },
    {
      target_name: "sg",
      platform: "longbridge",
      variable_scope: "environment",
      github_environment: "longbridge-sg",
    },
  ),
  true,
);

assert.equal(
  __test.resolvedVariableScope("default", { platform: "longbridge", target_name: "sg" }),
  "environment",
);

const updatedPluginModeOptions = __test.updateAccountOptionsDefaultStrategy(
  accountOptions,
  {
    platform: "longbridge",
    target_name: "sg",
    account_selector: "SG",
    strategy_profile: "tqqq_growth_income",
    execution_mode: "live",
    variable_scope: "default",
    plugin_mode: "none",
  },
);
assert.equal(updatedPluginModeOptions.changed, true);
assert.equal(updatedPluginModeOptions.options.longbridge[1].plugin_mode, "none");

const updatedOptionOverlayModeOptions = __test.updateAccountOptionsDefaultStrategy(
  accountOptions,
  {
    platform: "longbridge",
    target_name: "sg",
    account_selector: "SG",
    strategy_profile: "tqqq_growth_income",
    execution_mode: "live",
    variable_scope: "default",
    plugin_mode: "auto",
    option_overlay_mode: "disabled",
  },
);
assert.equal(updatedOptionOverlayModeOptions.changed, true);
assert.equal(updatedOptionOverlayModeOptions.options.longbridge[1].option_overlay_mode, "disabled");

const updatedCashOnlyModeOptions = __test.updateAccountOptionsDefaultStrategy(
  accountOptions,
  {
    platform: "longbridge",
    target_name: "sg",
    account_selector: "SG",
    strategy_profile: "tqqq_growth_income",
    execution_mode: "live",
    variable_scope: "default",
    plugin_mode: "auto",
    cash_only_execution_mode: "enabled",
  },
);
assert.equal(updatedCashOnlyModeOptions.changed, true);
assert.equal(updatedCashOnlyModeOptions.options.longbridge[1].cash_only_execution_mode, "enabled");

const updatedIbitZscoreModeOptions = __test.updateAccountOptionsDefaultStrategy(
  {
    ...accountOptions,
    ibkr: [
      {
        key: "ibit-primary",
        target_name: "ibit-primary",
        supported_domains: ["us_equity"],
        ibit_zscore_exit_mode: "live",
      },
    ],
  },
  {
    platform: "ibkr",
    target_name: "ibit-primary",
    strategy_profile: "ibit_smart_dca",
    execution_mode: "live",
    variable_scope: "repository",
    plugin_mode: "auto",
  },
);
assert.equal(updatedIbitZscoreModeOptions.changed, true);
assert.equal("ibit_zscore_exit_mode" in updatedIbitZscoreModeOptions.options.ibkr[0], false);

const kvWrites = new Map();
const syncResult = await __test.syncDefaultStrategyForAccount(
  {
    STRATEGY_SWITCH_CONFIG: {
      get: async (key) => key === "audit_log" ? "[]" : null,
      put: async (key, value) => kvWrites.set(key, value),
    },
  },
  accountOptions,
  {
    platform: "longbridge",
    target_name: "sg",
    account_selector: "SG",
    strategy_profile: "soxl_soxx_trend_income",
    execution_mode: "live",
    variable_scope: "default",
    plugin_mode: "auto",
  },
  { login: "pigbibi" },
);
assert.equal(syncResult.synced, true);
// default_strategy_profile is no longer persisted to KV after switch

const originalFetch = globalThis.fetch;
globalThis.fetch = async (url) => {
  const requestUrl = String(url);
  if (requestUrl.endsWith("/CLOUD_RUN_SERVICE_TARGETS_JSON")) {
    return new Response("", { status: 404 });
  }
  if (requestUrl.endsWith("/SCHWAB_MIN_RESERVED_CASH_USD")) {
    return new Response(JSON.stringify({ value: "150" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/SCHWAB_RESERVED_CASH_RATIO")) {
    return new Response(JSON.stringify({ value: "0.03" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/INCOME_LAYER_START_USD")) {
    return new Response(JSON.stringify({ value: "150000" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/INCOME_LAYER_MAX_RATIO")) {
    return new Response(JSON.stringify({ value: "0.95" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/OPTION_OVERLAY_ENABLED")) {
    return new Response(JSON.stringify({ value: "true" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/RUNTIME_TARGET_ENABLED")) {
    return new Response(JSON.stringify({ value: "false" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/DCA_MODE")) {
    return new Response(JSON.stringify({ value: "smart" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/DCA_BASE_INVESTMENT_USD")) {
    return new Response(JSON.stringify({ value: "500" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/RUNTIME_TARGET_JSON")) {
    return new Response(JSON.stringify({
      value: JSON.stringify({
        platform_id: "schwab",
        strategy_profile: "nasdaq_sp500_smart_dca",
        dry_run_only: false,
        account_scope: "schwab",
        service_name: "charles-schwab-quant-service",
        execution_mode: "live",
      }),
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }
  return new Response("", { status: 404 });
};
try {
  const currentStrategies = await __test.loadCurrentStrategies(
    { schwab: accountOptions.schwab },
    { RUNTIME_SETTINGS_DISPATCH_TOKEN: "test-token" },
  );
  assert.equal(currentStrategies.schwab.default.strategy_profile, "nasdaq_sp500_smart_dca");
  assert.equal(currentStrategies.schwab.default.execution_mode, "live");
  assert.equal(currentStrategies.schwab.default.min_reserved_cash_usd, "150");
  assert.equal(currentStrategies.schwab.default.reserved_cash_ratio, "0.03");
  assert.equal(currentStrategies.schwab.default.income_layer_start_usd, "150000");
  assert.equal(currentStrategies.schwab.default.income_layer_max_ratio, "0.95");
  assert.equal(currentStrategies.schwab.default.option_overlay_enabled, true);
  assert.equal(currentStrategies.schwab.default.runtime_target_enabled, false);
  assert.equal(currentStrategies.schwab.default.dca_mode, "smart");
  assert.equal(currentStrategies.schwab.default.dca_base_investment_usd, "500");
  assert.equal(currentStrategies.schwab.default.source, "RUNTIME_TARGET_JSON");
} finally {
  globalThis.fetch = originalFetch;
}

globalThis.fetch = async (url) => {
  const requestUrl = String(url);
  if (requestUrl.endsWith("/CLOUD_RUN_SERVICE_TARGETS_JSON")) {
    return new Response("", { status: 404 });
  }
  if (requestUrl.endsWith("/SCHWAB_MIN_RESERVED_CASH_USD")) {
    return new Response(JSON.stringify({ value: "150" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/SCHWAB_RESERVED_CASH_RATIO")) {
    return new Response(JSON.stringify({ value: "0.03" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/INCOME_LAYER_START_USD")) {
    return new Response(JSON.stringify({ value: "150000" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/INCOME_LAYER_MAX_RATIO")) {
    return new Response(JSON.stringify({ value: "0.95" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/OPTION_OVERLAY_ENABLED")) {
    return new Response(JSON.stringify({ value: "true" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/RUNTIME_TARGET_ENABLED")) {
    return new Response(JSON.stringify({ value: "TRUE" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/DCA_MODE")) {
    return new Response(JSON.stringify({ value: "smart" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/DCA_BASE_INVESTMENT_USD")) {
    return new Response(JSON.stringify({ value: "500" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  return new Response("", { status: 404 });
};
try {
  const currentStrategies = await __test.loadCurrentStrategies(
    { schwab: accountOptions.schwab },
    { RUNTIME_SETTINGS_DISPATCH_TOKEN: "test-token" },
  );
  assert.equal(currentStrategies.schwab.default.runtime_target_enabled, true);
} finally {
  globalThis.fetch = originalFetch;
}

globalThis.fetch = async (url) => {
  const requestUrl = String(url);
  if (requestUrl.endsWith("/CLOUD_RUN_SERVICE_TARGETS_JSON")) {
    return new Response(JSON.stringify({
      value: JSON.stringify({
        targets: [
          {
            service: "interactive-brokers-demo-ibkr-tqqq-service",
            ACCOUNT_GROUP: "demo-ibkr-tqqq",
            IBKR_MIN_RESERVED_CASH_USD: "150",
            IBKR_RESERVED_CASH_RATIO: "0.03",
            IBKR_CASH_ONLY_EXECUTION: "false",
            INCOME_LAYER_START_USD: "250000",
            INCOME_LAYER_MAX_RATIO: "0.55",
            OPTION_OVERLAY_ENABLED: "true",
            RUNTIME_TARGET_ENABLED: "false",
            DCA_MODE: "smart",
            DCA_BASE_INVESTMENT_USD: "700",
            IBIT_ZSCORE_EXIT_ENABLED: "true",
            IBIT_ZSCORE_EXIT_MODE: "live",
            runtime_target: {
              platform_id: "ibkr",
              strategy_profile: "ibit_smart_dca",
              dry_run_only: false,
              account_scope: "demo-ibkr-tqqq",
              service_name: "interactive-brokers-demo-ibkr-tqqq-service",
              execution_mode: "live",
            },
          },
        ],
      }),
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }
  return new Response("", { status: 404 });
};
try {
  const currentStrategies = await __test.loadCurrentStrategies(
    { ibkr: accountOptions.ibkr },
    { RUNTIME_SETTINGS_DISPATCH_TOKEN: "test-token" },
  );
  assert.equal(currentStrategies.ibkr["ibkr-primary"].strategy_profile, "ibit_smart_dca");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].min_reserved_cash_usd, "150");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].reserved_cash_ratio, "0.03");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].cash_only_execution, false);
  assert.equal(currentStrategies.ibkr["ibkr-primary"].income_layer_start_usd, "250000");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].income_layer_max_ratio, "0.55");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].option_overlay_enabled, true);
  assert.equal(currentStrategies.ibkr["ibkr-primary"].runtime_target_enabled, false);
  assert.equal(currentStrategies.ibkr["ibkr-primary"].dca_mode, "smart");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].dca_base_investment_usd, "700");
  assert.equal("ibit_zscore_exit_mode" in currentStrategies.ibkr["ibkr-primary"], false);
  assert.equal(currentStrategies.ibkr["ibkr-primary"].source, "CLOUD_RUN_SERVICE_TARGETS_JSON");
} finally {
  globalThis.fetch = originalFetch;
}

globalThis.fetch = async (url) => {
  const requestUrl = String(url);
  if (requestUrl.endsWith("/CLOUD_RUN_SERVICE_TARGETS_JSON")) {
    return new Response("", { status: 404 });
  }
  if (requestUrl.endsWith("/LONGBRIDGE_MIN_RESERVED_CASH_USD")) {
    return new Response(JSON.stringify({ value: "150" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/LONGBRIDGE_RESERVED_CASH_RATIO")) {
    return new Response(JSON.stringify({ value: "0.03" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  return new Response("", { status: 404 });
};
try {
  const currentStrategies = await __test.loadCurrentStrategies(
    { longbridge: [accountOptions.longbridge[0]] },
    { RUNTIME_SETTINGS_DISPATCH_TOKEN: "test-token" },
  );
  assert.equal(currentStrategies.longbridge.hk.strategy_profile, undefined);
  assert.equal(currentStrategies.longbridge.hk.min_reserved_cash_usd, "150");
  assert.equal(currentStrategies.longbridge.hk.reserved_cash_ratio, "0.03");
  assert.equal(currentStrategies.longbridge.hk.source, "RESERVED_CASH_VARIABLES");
} finally {
  globalThis.fetch = originalFetch;
}

globalThis.fetch = async (url) => {
  const requestUrl = String(url);
  if (requestUrl.endsWith("/CLOUD_RUN_SERVICE_TARGETS_JSON")) {
    return new Response("", { status: 404 });
  }
  if (requestUrl.endsWith("/IBKR_CASH_ONLY_EXECUTION")) {
    return new Response(JSON.stringify({ value: "false" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  return new Response("", { status: 404 });
};
try {
  const currentStrategies = await __test.loadCurrentStrategies(
    { ibkr: accountOptions.ibkr },
    { RUNTIME_SETTINGS_DISPATCH_TOKEN: "test-token" },
  );
  assert.equal(currentStrategies.ibkr["ibkr-primary"].cash_only_execution, false);
  assert.equal(currentStrategies.ibkr["ibkr-primary"].source, "CASH_ONLY_EXECUTION_VARIABLE");
} finally {
  globalThis.fetch = originalFetch;
}

globalThis.fetch = async (url) => {
  const requestUrl = String(url);
  if (requestUrl.includes("/LongBridgePlatform/actions/variables/CLOUD_RUN_SERVICE_TARGETS_JSON")) {
    return new Response(JSON.stringify({
      value: JSON.stringify({
        targets: [
          {
            service: "longbridge-quant-sg-service",
            strategy_profile: "russell_top50_leader_rotation",
            runtime_target: {
              platform_id: "longbridge",
              strategy_profile: "russell_top50_leader_rotation",
              account_scope: "SG",
              service_name: "longbridge-quant-sg-service",
              execution_mode: "live",
            },
          },
        ],
      }),
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }
  if (requestUrl.includes("/LongBridgePlatform/environments/longbridge-sg/variables/RUNTIME_TARGET_JSON")) {
    return new Response(JSON.stringify({
      value: JSON.stringify({
        platform_id: "longbridge",
        strategy_profile: "tqqq_growth_income",
        dry_run_only: false,
        account_scope: "SG",
        service_name: "longbridge-quant-sg-service",
        execution_mode: "live",
      }),
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }
  if (requestUrl.includes("/LongBridgePlatform/environments/longbridge-sg/variables/LONGBRIDGE_MIN_RESERVED_CASH_USD")) {
    return new Response(JSON.stringify({ value: "25" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.includes("/LongBridgePlatform/environments/longbridge-sg/variables/LONGBRIDGE_RESERVED_CASH_RATIO")) {
    return new Response(JSON.stringify({ value: "0.04" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.includes("/InteractiveBrokersPlatform/actions/variables/CLOUD_RUN_SERVICE_TARGETS_JSON")) {
    return new Response(JSON.stringify({
      value: JSON.stringify({
        targets: [
          {
            service: "interactive-brokers-demo-ibkr-tqqq-service",
            ACCOUNT_GROUP: "demo-ibkr-tqqq",
            IBKR_MIN_RESERVED_CASH_USD: "150",
            IBKR_RESERVED_CASH_RATIO: "0.03",
            runtime_target: {
              platform_id: "ibkr",
              strategy_profile: "tqqq_growth_income",
              dry_run_only: false,
              account_scope: "demo-ibkr-tqqq",
              service_name: "interactive-brokers-demo-ibkr-tqqq-service",
              execution_mode: "live",
            },
          },
        ],
      }),
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }
  if (requestUrl.includes("/CharlesSchwabPlatform/actions/variables/RUNTIME_TARGET_JSON")) {
    return new Response(JSON.stringify({
      value: JSON.stringify({
        platform_id: "schwab",
        strategy_profile: "soxl_soxx_trend_income",
        dry_run_only: false,
        account_scope: "default",
        service_name: "charles-schwab-quant-service",
        execution_mode: "live",
      }),
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }
  if (requestUrl.includes("/CharlesSchwabPlatform/actions/variables/SCHWAB_MIN_RESERVED_CASH_USD")) {
    return new Response(JSON.stringify({ value: "150" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.includes("/CharlesSchwabPlatform/actions/variables/SCHWAB_RESERVED_CASH_RATIO")) {
    return new Response(JSON.stringify({ value: "0.03" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.includes("/FirstradePlatform/actions/variables/RUNTIME_TARGET_JSON")) {
    return new Response(JSON.stringify({
      value: JSON.stringify({
        platform_id: "firstrade",
        strategy_profile: "ibit_smart_dca",
        dry_run_only: false,
        account_scope: "US",
        service_name: "firstrade-quant-service",
        execution_mode: "live",
      }),
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }
  if (requestUrl.includes("/FirstradePlatform/actions/variables/FIRSTRADE_MIN_RESERVED_CASH_USD")) {
    return new Response(JSON.stringify({ value: "50" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.includes("/FirstradePlatform/actions/variables/FIRSTRADE_RESERVED_CASH_RATIO")) {
    return new Response(JSON.stringify({ value: "0.02" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.includes("/FirstradePlatform/actions/variables/DCA_MODE")) {
    return new Response(JSON.stringify({ value: "fixed" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.includes("/FirstradePlatform/actions/variables/DCA_BASE_INVESTMENT_USD")) {
    return new Response(JSON.stringify({ value: "50" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.includes("/FirstradePlatform/actions/variables/IBIT_ZSCORE_EXIT_ENABLED")) {
    return new Response(JSON.stringify({ value: "true" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  return new Response("", { status: 404 });
};
try {
  const currentStrategies = await __test.loadCurrentStrategies(
    {
      longbridge: [accountOptions.longbridge[1]],
      ibkr: accountOptions.ibkr,
      schwab: accountOptions.schwab,
      firstrade: accountOptions.firstrade,
    },
    { RUNTIME_SETTINGS_DISPATCH_TOKEN: "test-token" },
  );
  assert.equal(currentStrategies.longbridge.sg.strategy_profile, "tqqq_growth_income");
  assert.equal(currentStrategies.longbridge.sg.min_reserved_cash_usd, "25");
  assert.equal(currentStrategies.longbridge.sg.reserved_cash_ratio, "0.04");
  assert.equal(currentStrategies.longbridge.sg.source, "RUNTIME_TARGET_JSON");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].strategy_profile, "tqqq_growth_income");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].min_reserved_cash_usd, "150");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].reserved_cash_ratio, "0.03");
  assert.equal(currentStrategies.ibkr["ibkr-primary"].source, "CLOUD_RUN_SERVICE_TARGETS_JSON");
  assert.equal(currentStrategies.schwab.default.strategy_profile, "soxl_soxx_trend_income");
  assert.equal(currentStrategies.schwab.default.min_reserved_cash_usd, "150");
  assert.equal(currentStrategies.schwab.default.reserved_cash_ratio, "0.03");
  assert.equal(currentStrategies.firstrade.default.strategy_profile, "ibit_smart_dca");
  assert.equal(currentStrategies.firstrade.default.min_reserved_cash_usd, "50");
  assert.equal(currentStrategies.firstrade.default.reserved_cash_ratio, "0.02");
  assert.equal(currentStrategies.firstrade.default.dca_mode, "fixed");
  assert.equal(currentStrategies.firstrade.default.dca_base_investment_usd, "50");
  assert.equal("ibit_zscore_exit_mode" in currentStrategies.firstrade.default, false);
} finally {
  globalThis.fetch = originalFetch;
}

let releaseReservedVariables;
let reservedVariableRequests = 0;
let reservedVariablesFinished = false;
let runtimeTargetStartedBeforeReservedVariablesFinished = false;
const reservedVariablesGate = new Promise((resolve) => {
  releaseReservedVariables = () => {
    reservedVariablesFinished = true;
    resolve();
  };
});
const reservedVariableFallback = setTimeout(releaseReservedVariables, 100);
globalThis.fetch = async (url) => {
  const requestUrl = String(url);
  if (requestUrl.endsWith("/CLOUD_RUN_SERVICE_TARGETS_JSON")) {
    return new Response("", { status: 404 });
  }
  if (requestUrl.endsWith("/SCHWAB_MIN_RESERVED_CASH_USD") || requestUrl.endsWith("/SCHWAB_RESERVED_CASH_RATIO")) {
    reservedVariableRequests += 1;
    await reservedVariablesGate;
    return new Response(JSON.stringify({ value: requestUrl.endsWith("/SCHWAB_RESERVED_CASH_RATIO") ? "0.03" : "150" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (requestUrl.endsWith("/RUNTIME_TARGET_JSON")) {
    runtimeTargetStartedBeforeReservedVariablesFinished = reservedVariableRequests === 2 && !reservedVariablesFinished;
    releaseReservedVariables();
    return new Response(JSON.stringify({
      value: JSON.stringify({
        platform_id: "schwab",
        strategy_profile: "soxl_soxx_trend_income",
        dry_run_only: false,
        account_scope: "schwab",
        service_name: "charles-schwab-quant-service",
        execution_mode: "live",
      }),
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }
  return new Response("", { status: 404 });
};
try {
  const currentStrategies = await __test.loadCurrentStrategies(
    { schwab: accountOptions.schwab },
    { RUNTIME_SETTINGS_DISPATCH_TOKEN: "test-token" },
  );
  assert.equal(currentStrategies.schwab.default.min_reserved_cash_usd, "150");
  assert.equal(currentStrategies.schwab.default.reserved_cash_ratio, "0.03");
  assert.equal(currentStrategies.schwab.default.strategy_profile, "soxl_soxx_trend_income");
} finally {
  clearTimeout(reservedVariableFallback);
  globalThis.fetch = originalFetch;
}

const longbridgeHk = __test.assertConfiguredAccount(
  {
    platform: "longbridge",
    target_name: "hk",
    account_selector: "HK",
    strategy_profile: "hk_low_vol_dividend_quality_snapshot",
  },
  accountOptions,
);
__test.assertStrategyAllowedForAccount(
  {
    platform: "longbridge",
    strategy_profile: "hk_low_vol_dividend_quality_snapshot",
  },
  longbridgeHk,
  strategyProfiles,
);

const ibkrAccount = __test.assertConfiguredAccount(
  {
    platform: "ibkr",
    target_name: "ibkr-primary",
    account_selector: "DEMO_IBKR_PRIMARY",
    deployment_selector: "demo-ibkr-tqqq",
    account_scope: "demo-ibkr-tqqq",
    service_name: "interactive-brokers-demo-ibkr-tqqq-service",
    strategy_profile: "tqqq_growth_income",
  },
  accountOptions,
);
__test.assertStrategyAllowedForAccount(
  {
    platform: "ibkr",
    strategy_profile: "tqqq_growth_income",
  },
  ibkrAccount,
  strategyProfiles,
);
__test.assertStrategyAllowedForAccount(
  {
    platform: "ibkr",
    strategy_profile: "hk_low_vol_dividend_quality_snapshot",
  },
  ibkrAccount,
  strategyProfiles,
);

const schwabAccount = __test.assertConfiguredAccount(
  {
    platform: "schwab",
    target_name: "default",
    strategy_profile: "tqqq_growth_income",
  },
  accountOptions,
);
__test.assertStrategyAllowedForAccount(
  {
    platform: "schwab",
    strategy_profile: "tqqq_growth_income",
  },
  schwabAccount,
  strategyProfiles,
);
assert.throws(
  () => __test.assertStrategyAllowedForAccount(
    {
      platform: "schwab",
      strategy_profile: "hk_low_vol_dividend_quality_snapshot",
    },
    schwabAccount,
    strategyProfiles,
  ),
  /not supported/,
);

const healthStore = new Map();
const healthKv = {
  async get(key) { return healthStore.get(key) || null; },
  async put(key, value) { healthStore.set(key, value); },
};
const healthSyncValue = ["sync", "value"].join("-");
const sessionValue = ["session", "value"].join("-");
const sensitiveReviewKey = ["leaked", ["t", "o", "k", "e", "n"].join("")].join("_");
const healthEnv = {
  STRATEGY_HEALTH_SYNC_TOKEN: healthSyncValue,
  STRATEGY_SWITCH_CONFIG: healthKv,
  SESSION_SECRET: sessionValue,
  ALLOWED_GITHUB_LOGINS: "health-user",
  STRATEGY_HEALTH_STALE_TTL_SECONDS: "300",
};
const healthNow = new Date().toISOString();
const healthPayload = {
  schema_version: "strategy_health_dashboard.v1",
  generated_at: healthNow,
  computed_at: healthNow,
  data_status: "ready",
  strategies: [{
    profile: "demo_trend",
    domain: "crypto",
    as_of: "2026-07-11",
    status: "healthy",
    score: 91,
    components: { performance: 90, risk: 92, decay: null, stability: 91, operations: 93 },
    decision: { code: "human_live_gate", label: "等待人工确认", reason: "健康不等于已批准 live。" },
    review: {
      requested_stage: "live_candidate",
      evidence_package_id: "evidence-1",
      validation: { oos_passed: true },
      risk: { mdd: 0.12 },
      kelly_readiness: { level: "K1" },
      [sensitiveReviewKey]: "redacted-marker",
    },
    freshness: { status: "fresh", age_seconds: 30 },
    source_revision: "abc123",
  }],
  policy: { mode: "read_only", notice: "健康不等于已批准 live。" },
  errors: ["safe_notice", "not safe error"],
};
const sessionCookie = await __test.makeSession("health-user", [], healthEnv);
const healthCookieHeaders = { Cookie: `qsl_switch_session=${sessionCookie}` };

const unauthorizedHealthRead = await worker.fetch(
  new Request("https://switch.example/api/strategy-health"),
  healthEnv,
);
assert.equal(unauthorizedHealthRead.status, 401);

const wrongHealthToken = await worker.fetch(
  new Request("https://switch.example/api/internal/sync-strategy-health", {
    method: "POST",
    headers: { Authorization: "Bearer other-value", "Content-Type": "application/json" },
    body: JSON.stringify(healthPayload),
  }),
  healthEnv,
);
assert.equal(wrongHealthToken.status, 401);

const oversizedHealthPayload = await worker.fetch(
  new Request("https://switch.example/api/internal/sync-strategy-health", {
    method: "POST",
    headers: { Authorization: `Bearer ${healthSyncValue}`, "Content-Type": "application/json" },
    body: JSON.stringify({ schema_version: "strategy_health_dashboard.v1", padding: "x".repeat(256 * 1024) }),
  }),
  healthEnv,
);
assert.equal(oversizedHealthPayload.status, 413);

const healthSync = await worker.fetch(
  new Request("https://switch.example/api/internal/sync-strategy-health", {
    method: "POST",
    headers: { Authorization: `Bearer ${healthSyncValue}`, "Content-Type": "application/json" },
    body: JSON.stringify(healthPayload),
  }),
  healthEnv,
);
assert.equal(healthSync.status, 200);
assert.equal((await healthSync.json()).strategy_count, 1);

const healthRead = await worker.fetch(
  new Request("https://switch.example/api/strategy-health", { headers: healthCookieHeaders }),
  healthEnv,
);
assert.equal(healthRead.status, 200);
const healthReadPayload = await healthRead.json();
assert.equal(healthReadPayload.data_status, "ready");
assert.equal(healthReadPayload.strategies[0].review[sensitiveReviewKey], undefined);
assert.deepEqual(healthReadPayload.errors, ["safe_notice"]);

healthPayload.generated_at = new Date().toISOString();
healthPayload.computed_at = "2020-01-01T00:00:00.000Z";
await worker.fetch(
  new Request("https://switch.example/api/internal/sync-strategy-health", {
    method: "POST",
    headers: { Authorization: `Bearer ${healthSyncValue}`, "Content-Type": "application/json" },
    body: JSON.stringify(healthPayload),
  }),
  healthEnv,
);
const staleHealthRead = await worker.fetch(
  new Request("https://switch.example/api/strategy-health", { headers: healthCookieHeaders }),
  healthEnv,
);
assert.equal((await staleHealthRead.json()).data_status, "stale");

healthPayload.data_status = "unavailable";
await worker.fetch(
  new Request("https://switch.example/api/internal/sync-strategy-health", {
    method: "POST",
    headers: { Authorization: `Bearer ${healthSyncValue}`, "Content-Type": "application/json" },
    body: JSON.stringify(healthPayload),
  }),
  healthEnv,
);
const unavailableHealthRead = await worker.fetch(
  new Request("https://switch.example/api/strategy-health", { headers: healthCookieHeaders }),
  healthEnv,
);
const unavailableHealthPayload = await unavailableHealthRead.json();
assert.equal(unavailableHealthPayload.data_status, "unavailable");
assert.equal(unavailableHealthPayload.summary.strategy_count, 0);
assert.deepEqual(unavailableHealthPayload.strategies, []);

const noKvHealthRead = await worker.fetch(
  new Request("https://switch.example/api/strategy-health", { headers: healthCookieHeaders }),
  { ...healthEnv, STRATEGY_SWITCH_CONFIG: undefined },
);
assert.equal(noKvHealthRead.status, 200);
const noKvPayload = await noKvHealthRead.json();
assert.equal(noKvPayload.data_status, "unavailable");
assert.equal(noKvPayload.summary.strategy_count, 0);
