// Generated by python/scripts/build_platform_config.py; single source of truth.
// Source: platform-config.json

export const PLATFORM_CONFIG = {
  "longbridge": {
    "dry_run_only": false,
    "margin_policy": true,
    "reserved_cash": true,
    "income_layer": true,
    "option_overlay": true,
    "dca": true,
    "execution_mode": "live",
    "service_name": "",
    "default_execution_mode": "live"
  },
  "ibkr": {
    "dry_run_only": false,
    "margin_policy": true,
    "reserved_cash": true,
    "income_layer": true,
    "option_overlay": true,
    "dca": true,
    "execution_mode": "live",
    "service_name": "",
    "default_execution_mode": "live"
  },
  "schwab": {
    "dry_run_only": false,
    "margin_policy": true,
    "reserved_cash": true,
    "income_layer": true,
    "option_overlay": true,
    "dca": true,
    "execution_mode": "live",
    "service_name": "charles-schwab-quant-service",
    "default_execution_mode": "live"
  },
  "firstrade": {
    "dry_run_only": false,
    "margin_policy": true,
    "reserved_cash": true,
    "income_layer": true,
    "option_overlay": true,
    "dca": true,
    "execution_mode": "live",
    "service_name": "firstrade-quant-service",
    "default_execution_mode": "live"
  },
  "qmt": {
    "dry_run_only": true,
    "margin_policy": false,
    "reserved_cash": false,
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "execution_mode": "paper",
    "service_name": "qmt-quant-service",
    "default_execution_mode": "paper"
  },
  "binance": {
    "dry_run_only": false,
    "margin_policy": false,
    "reserved_cash": false,
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "execution_mode": "live",
    "service_name": "",
    "default_execution_mode": "live"
  }
};

export const DEFAULT_ACCOUNT_OPTIONS = {
  "longbridge": [
    {
      "key": "preview",
      "label": "LongBridge",
      "target_name": "preview",
      "supported_domains": [
        "us_equity",
        "hk_equity"
      ],
      "cash_currency": "USD",
      "default_strategy_profile": "tqqq_growth_income",
      "default_execution_mode": "live",
      "service_name": ""
    }
  ],
  "ibkr": [
    {
      "key": "preview",
      "label": "IBKR",
      "target_name": "preview",
      "supported_domains": [
        "us_equity",
        "hk_equity"
      ],
      "cash_currency": "USD",
      "default_strategy_profile": "soxl_soxx_trend_income",
      "default_execution_mode": "live",
      "service_name": ""
    }
  ],
  "schwab": [
    {
      "key": "preview",
      "label": "Schwab",
      "target_name": "preview",
      "supported_domains": [
        "us_equity"
      ],
      "cash_currency": "USD",
      "default_strategy_profile": "soxl_soxx_trend_income",
      "default_execution_mode": "live",
      "service_name": "charles-schwab-quant-service"
    }
  ],
  "firstrade": [
    {
      "key": "preview",
      "label": "Firstrade",
      "target_name": "preview",
      "supported_domains": [
        "us_equity"
      ],
      "cash_currency": "USD",
      "default_strategy_profile": "ibit_smart_dca",
      "default_execution_mode": "live",
      "service_name": "firstrade-quant-service"
    }
  ],
  "qmt": [
    {
      "key": "default",
      "label": "QMT",
      "target_name": "default",
      "supported_domains": [
        "cn_equity"
      ],
      "cash_currency": "CNY",
      "default_strategy_profile": "cn_industry_etf_rotation",
      "service_name": "qmt-quant-service",
      "default_execution_mode": "paper"
    }
  ],
  "binance": [
    {
      "key": "default",
      "label": "Binance",
      "target_name": "default",
      "supported_domains": [
        "crypto"
      ],
      "cash_currency": "USD",
      "default_strategy_profile": "crypto_equity_combo",
      "service_name": "",
      "default_execution_mode": "live"
    }
  ]
};

export const PLATFORM_REPOSITORIES = {
  "longbridge": "QuantStrategyLab/LongBridgePlatform",
  "ibkr": "QuantStrategyLab/InteractiveBrokersPlatform",
  "schwab": "QuantStrategyLab/CharlesSchwabPlatform",
  "firstrade": "QuantStrategyLab/FirstradePlatform",
  "qmt": "QuantStrategyLab/QmtPlatform",
  "binance": "QuantStrategyLab/BinancePlatform"
};

export const DCA_SUPPORTED_PLATFORMS = new Set(["longbridge", "ibkr", "schwab", "firstrade"]);

export const DEFAULT_VARIABLE_SCOPES = {
  "longbridge": "environment",
  "ibkr": "repository",
  "schwab": "repository",
  "firstrade": "repository",
  "qmt": "repository",
  "binance": "repository"
};

export const DOMAIN_LABELS = {
  "us_equity": {
    "zh": "美股",
    "en": "US Equity"
  },
  "hk_equity": {
    "zh": "港股",
    "en": "HK Equity"
  },
  "cn_equity": {
    "zh": "A股",
    "en": "CN A-share"
  },
  "crypto": {
    "zh": "加密",
    "en": "Crypto"
  }
};

export const FALLBACK_INCOME_LAYER_DEFAULTS = {
  "tqqq_growth_income": {
    "startUsd": 250000,
    "maxRatio": "0.55",
    "allocations": {
      "SCHD": 0.3,
      "DGRO": 0.2,
      "SGOV": 0.4,
      "SPYI": 0.08,
      "QQQI": 0.02
    }
  },
  "soxl_soxx_trend_income": {
    "startUsd": 150000,
    "maxRatio": "0.95",
    "allocations": {
      "SCHD": 0.15,
      "DGRO": 0.1,
      "SGOV": 0.7,
      "SPYI": 0.04,
      "QQQI": 0.01
    }
  },
  "global_etf_rotation": {
    "startUsd": 500000,
    "maxRatio": "0.15",
    "allocations": {
      "SCHD": 0.4,
      "DGRO": 0.25,
      "SGOV": 0.3,
      "SPYI": 0.05
    }
  },
  "russell_top50_leader_rotation": {
    "startUsd": 300000,
    "maxRatio": "0.25",
    "allocations": {
      "SCHD": 0.45,
      "DGRO": 0.3,
      "SGOV": 0.25
    }
  },
  "us_equity_combo": {
    "startUsd": 300000,
    "maxRatio": "0.25",
    "allocations": {
      "SCHD": 0.25,
      "DGRO": 0.25,
      "SGOV": 0.2,
      "SPYI": 0.15,
      "QQQI": 0.15
    }
  }
};

export const FALLBACK_OPTION_OVERLAY_DEFAULTS = {
  "tqqq_growth_income": {
    "liveGate": "promotion_required",
    "liveStatus": "research_only",
    "families": [
      {
        "family": "growth",
        "recipe": "tqqq_leaps_growth_v1",
        "startUsd": "250000",
        "ratio": "0.03",
        "ratioKind": "budget"
      }
    ]
  },
  "soxl_soxx_trend_income": {
    "liveGate": "promotion_required",
    "liveStatus": "research_only",
    "families": [
      {
        "family": "income",
        "recipe": "soxx_put_credit_spread_income_v1",
        "startUsd": "150000",
        "ratio": "0.01",
        "ratioKind": "risk"
      }
    ]
  },
  "global_etf_rotation": {
    "liveGate": "promotion_required",
    "liveStatus": "research_only",
    "families": [
      {
        "family": "growth",
        "recipe": "spy_leaps_growth_v1",
        "startUsd": "500000",
        "ratio": "0.015",
        "ratioKind": "budget"
      }
    ]
  },
  "russell_top50_leader_rotation": {
    "liveGate": "promotion_required",
    "liveStatus": "research_only",
    "families": [
      {
        "family": "growth",
        "recipe": "spy_leaps_growth_v1",
        "startUsd": "300000",
        "ratio": "0.015",
        "ratioKind": "budget"
      }
    ]
  },
  "us_equity_combo": {
    "liveGate": "promotion_required",
    "liveStatus": "research_only",
    "families": [
      {
        "family": "growth",
        "recipe": "spy_leaps_growth_v1",
        "startUsd": "300000",
        "ratio": "0.015",
        "ratioKind": "budget"
      }
    ]
  }
};

export const DCA_PROFILE_DEFAULTS = {
  "nasdaq_sp500_smart_dca": {
    "defaultMode": "fixed",
    "defaultBaseInvestmentUsd": "1000"
  },
  "ibit_smart_dca": {
    "defaultMode": "fixed",
    "defaultBaseInvestmentUsd": "1000"
  }
};

export const STRATEGY_FEATURES = {
  "tqqq_growth_income": {
    "income_layer": true,
    "option_overlay": true,
    "dca": false,
    "combo": false
  },
  "soxl_soxx_trend_income": {
    "income_layer": true,
    "option_overlay": true,
    "dca": false,
    "combo": false
  },
  "nasdaq_sp500_smart_dca": {
    "income_layer": false,
    "option_overlay": false,
    "dca": true,
    "combo": false
  },
  "ibit_smart_dca": {
    "income_layer": false,
    "option_overlay": false,
    "dca": true,
    "combo": false
  },
  "global_etf_rotation": {
    "income_layer": true,
    "option_overlay": true,
    "dca": false,
    "combo": false
  },
  "russell_top50_leader_rotation": {
    "income_layer": true,
    "option_overlay": true,
    "dca": false,
    "combo": false
  },
  "us_equity_combo": {
    "income_layer": true,
    "option_overlay": true,
    "dca": false,
    "combo": true
  },
  "us_equity_combo_leveraged": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": true
  },
  "hk_global_etf_tactical_rotation": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": false
  },
  "hk_low_vol_dividend_quality_snapshot": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": false
  },
  "hk_equity_combo": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": true
  },
  "cn_industry_etf_rotation": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": false
  },
  "cn_industry_etf_rotation_aggressive": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": false
  },
  "cn_stock_momentum_rotation": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": false
  },
  "cn_dividend_quality_snapshot": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": false
  },
  "cn_equity_combo": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": true
  },
  "crypto_btc_dca": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": false
  },
  "crypto_trend_rotation": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": false
  },
  "crypto_equity_combo": {
    "income_layer": false,
    "option_overlay": false,
    "dca": false,
    "combo": true
  }
};

export const PLATFORM_MIN_RESERVED_CASH_VARIABLES = {
  "longbridge": "LONGBRIDGE_MIN_RESERVED_CASH_USD",
  "ibkr": "IBKR_MIN_RESERVED_CASH_USD",
  "schwab": "SCHWAB_MIN_RESERVED_CASH_USD",
  "firstrade": "FIRSTRADE_MIN_RESERVED_CASH_USD"
};

export const PLATFORM_RESERVED_CASH_RATIO_VARIABLES = {
  "longbridge": "LONGBRIDGE_RESERVED_CASH_RATIO",
  "ibkr": "IBKR_RESERVED_CASH_RATIO",
  "schwab": "SCHWAB_RESERVED_CASH_RATIO",
  "firstrade": "FIRSTRADE_RESERVED_CASH_RATIO"
};
