#!/usr/bin/env python3
"""Keep the console's configuration bootstrap as a same-origin script.

The Worker serializes the non-secret configuration from ``config.js`` at
``/bootstrap-config.js``. Keeping this loader external lets the page retain
its strict ``script-src 'self'`` CSP without a hash or ``unsafe-inline``.
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "web" / "strategy-switch-console" / "index.html"
MARKER = "<!-- Generated by inject_platform_config.py -->"
BOOTSTRAP = '<script src="/bootstrap-config.js"></script>'


def main() -> int:
    html = SOURCE.read_text(encoding="utf-8")
    replacement = f"{MARKER}\n{BOOTSTRAP}"
    legacy_script = html.find('<script id="platform-config">')

    if legacy_script >= 0:
        start = legacy_script
        prefix = html[:start].rstrip()
        if prefix.endswith(MARKER):
            start = prefix.rfind(MARKER)
        end = html.find("</script>", legacy_script)
        if end < 0:
            raise RuntimeError("platform-config script is missing its closing tag")
        html = html[:start].rstrip() + "\n\n" + replacement + html[end + len("</script>"):]
    elif BOOTSTRAP not in html:
        head_end = html.find("</head>")
        if head_end < 0:
            raise RuntimeError("index.html is missing </head>")
        html = html[:head_end] + "\n" + replacement + "\n" + html[head_end:]

    SOURCE.write_text(html, encoding="utf-8")
    print("Configured same-origin bootstrap-config.js loader")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
