#!/usr/bin/env python3
"""Embed strategy-switch console page/app assets as Worker modules.

Catalog authority is platform-config.json via build_platform_config.py.
This script only packages HTML/CSS/JS sources into importable modules.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "web" / "strategy-switch-console" / "index.html"
TARGET = ROOT / "web" / "strategy-switch-console" / "page_asset.js"
APP_CSS_SOURCE = ROOT / "web" / "strategy-switch-console" / "app.css"
APP_CSS_TARGET = ROOT / "web" / "strategy-switch-console" / "app_css.js"
APP_JS_SOURCE = ROOT / "web" / "strategy-switch-console" / "app.js"
APP_JS_TARGET = ROOT / "web" / "strategy-switch-console" / "app_js.js"


def _write_asset(path: Path, export_name: str, value: str) -> None:
    path.write_text(
        "// Generated by python/scripts/sync_strategy_switch_page_asset.py; do not edit by hand.\n"
        f"export const {export_name} = {json.dumps(value, ensure_ascii=False)};\n",
        encoding="utf-8",
    )


def main() -> int:
    _write_asset(TARGET, "PAGE_HTML", SOURCE.read_text(encoding="utf-8"))
    _write_asset(APP_CSS_TARGET, "APP_CSS", APP_CSS_SOURCE.read_text(encoding="utf-8"))
    _write_asset(APP_JS_TARGET, "APP_JS", APP_JS_SOURCE.read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
