#!/usr/bin/env python3
"""Embed the strategy switch Worker HTML as a module asset."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "web" / "strategy-switch-console" / "index.html"
TARGET = ROOT / "web" / "strategy-switch-console" / "page_asset.js"
PROFILE_SOURCE = ROOT / "web" / "strategy-switch-console" / "strategy-profiles.example.json"
PROFILE_TARGET = ROOT / "web" / "strategy-switch-console" / "strategy_profiles_asset.js"
APP_CSS_SOURCE = ROOT / "web" / "strategy-switch-console" / "app.css"
APP_CSS_TARGET = ROOT / "web" / "strategy-switch-console" / "app_css.js"
APP_JS_SOURCE = ROOT / "web" / "strategy-switch-console" / "app.js"
APP_JS_TARGET = ROOT / "web" / "strategy-switch-console" / "app_js.js"
CONFIG_PATH = ROOT / "platform-config.json"


def _normalize_allowed_execution_modes(raw_modes: object) -> list[str]:
    if raw_modes is None:
        return ["live", "paper", "dry_run"]
    if isinstance(raw_modes, str):
        modes = [raw_modes.strip()]
    elif isinstance(raw_modes, list):
        modes = [str(mode).strip() for mode in raw_modes]
    elif isinstance(raw_modes, tuple):
        modes = [str(mode).strip() for mode in raw_modes]
    elif isinstance(raw_modes, set):
        modes = [str(mode).strip() for mode in sorted(raw_modes)]
    else:
        modes = ["live", "paper", "dry_run"]
    modes = [mode for mode in modes if mode]
    return modes if modes else ["live", "paper", "dry_run"]


def _load_strategy_config_fields() -> dict[str, dict]:
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    raw_strategies = config.get("strategies", {})
    if not isinstance(raw_strategies, dict):
        return {}
    return {str(profile): dict(sdata) for profile, sdata in raw_strategies.items() if isinstance(sdata, dict)}


def _enrich_profiles_from_config(profiles: list[dict]) -> list[dict]:
    strategy_config = _load_strategy_config_fields()
    enriched = []
    for profile in profiles:
        if not isinstance(profile, dict):
            enriched.append(profile)
            continue
        item = dict(profile)
        sid = str(item.get("profile", "")).strip()
        config_fields = strategy_config.get(sid, {})
        runtime_enabled = config_fields.get("runtime_enabled", item.get("runtime_enabled", True))
        lifecycle_stage = str(
            config_fields.get("lifecycle_stage")
            or item.get("lifecycle_stage")
            or ("runtime_enabled" if runtime_enabled else "research_backtest_only")
        ).strip()
        can_switch_live = config_fields.get(
            "can_switch_live",
            item.get("can_switch_live", runtime_enabled and lifecycle_stage == "runtime_enabled"),
        )
        blocked_live_reason = config_fields.get("blocked_live_reason", item.get("blocked_live_reason"))
        if blocked_live_reason is None and not can_switch_live:
            blocked_live_reason = lifecycle_stage or "not_runtime_enabled"
        item.setdefault("lifecycle_stage", lifecycle_stage)
        item.setdefault("can_switch_live", can_switch_live)
        item.setdefault(
            "allowed_execution_modes",
            _normalize_allowed_execution_modes(config_fields.get("allowed_execution_modes")),
        )
        item.setdefault(
            "blocked_live_reason",
            "" if blocked_live_reason is None else str(blocked_live_reason).strip(),
        )
        item.setdefault("runtime_enabled", runtime_enabled)
        enriched.append(item)
    return enriched


def main() -> int:
    html = SOURCE.read_text(encoding="utf-8")
    page_payload = (
        "// Generated by scripts/sync_strategy_switch_page_asset.py; do not edit by hand.\n"
        f"export const PAGE_HTML = {json.dumps(html, ensure_ascii=False)};\n"
    )
    TARGET.write_text(page_payload, encoding="utf-8")

    profiles = json.loads(PROFILE_SOURCE.read_text(encoding="utf-8"))
    profiles = _enrich_profiles_from_config(profiles)
    profile_payload = (
        "// Generated by scripts/sync_strategy_switch_page_asset.py; do not edit by hand.\n"
        f"export const DEFAULT_STRATEGY_PROFILES = {json.dumps(profiles, ensure_ascii=False)};\n"
    )
    PROFILE_TARGET.write_text(profile_payload, encoding="utf-8")

    app_css = APP_CSS_SOURCE.read_text(encoding="utf-8")
    APP_CSS_TARGET.write_text(
        f"// Generated — CSS asset\nexport const APP_CSS = {json.dumps(app_css, ensure_ascii=False)};\n",
        encoding="utf-8",
    )

    app_js = APP_JS_SOURCE.read_text(encoding="utf-8")
    APP_JS_TARGET.write_text(
        f"// Generated — JS asset\nexport const APP_JS = {json.dumps(app_js, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
