#!/usr/bin/env python3
"""Embed the strategy switch Worker HTML as a module asset."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "web" / "strategy-switch-console" / "index.html"
TARGET = ROOT / "web" / "strategy-switch-console" / "page_asset.js"
PROFILE_SOURCE = ROOT / "web" / "strategy-switch-console" / "strategy-profiles.example.json"
PROFILE_TARGET = ROOT / "web" / "strategy-switch-console" / "strategy_profiles_asset.js"
APP_CSS_SOURCE = ROOT / "web" / "strategy-switch-console" / "app.css"
APP_CSS_TARGET = ROOT / "web" / "strategy-switch-console" / "app_css.js"
APP_JS_SOURCE = ROOT / "web" / "strategy-switch-console" / "app.js"
APP_JS_TARGET = ROOT / "web" / "strategy-switch-console" / "app_js.js"


def main() -> int:
    html = SOURCE.read_text(encoding="utf-8")
    page_payload = (
        "// Generated by scripts/sync_strategy_switch_page_asset.py; do not edit by hand.\n"
        f"export const PAGE_HTML = {json.dumps(html, ensure_ascii=False)};\n"
    )
    TARGET.write_text(page_payload, encoding="utf-8")

    profiles = json.loads(PROFILE_SOURCE.read_text(encoding="utf-8"))
    profile_payload = (
        "// Generated by scripts/sync_strategy_switch_page_asset.py; do not edit by hand.\n"
        f"export const DEFAULT_STRATEGY_PROFILES = {json.dumps(profiles, ensure_ascii=False)};\n"
    )
    PROFILE_TARGET.write_text(profile_payload, encoding="utf-8")

    app_css = APP_CSS_SOURCE.read_text(encoding="utf-8")
    APP_CSS_TARGET.write_text(
        "// Generated — CSS asset\n"
        f"export const APP_CSS = {json.dumps(app_css, ensure_ascii=False)};\n",
        encoding="utf-8",
    )

    app_js = APP_JS_SOURCE.read_text(encoding="utf-8")
    APP_JS_TARGET.write_text(
        "// Generated — JS asset\n"
        f"export const APP_JS = {json.dumps(app_js, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
