#!/usr/bin/env python3
"""Embed the strategy switch Worker HTML as a module asset."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "web" / "strategy-switch-console" / "index.html"
TARGET = ROOT / "web" / "strategy-switch-console" / "page_asset.js"


def main() -> int:
    html = SOURCE.read_text(encoding="utf-8")
    payload = (
        "// Generated by scripts/sync_strategy_switch_page_asset.py; do not edit by hand.\n"
        f"export const PAGE_HTML = {json.dumps(html, ensure_ascii=False)};\n"
    )
    TARGET.write_text(payload, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
